### ISSUE TITLE
Giphys not counting as response on threads

### ISSUE THREAD

**Issue by lucaswhitman** [GetStream/stream-chat-react-native#1004]
**Describe the bug**

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native): 3.9.2
- react-native or expo version: 0.65.1
- Device/Emulator (android/ios) and OS version: iOS 15

**To Reproduce**

1. Navigate to thread
2. Respond via message
3. Respond via giphy
4. Return to parent message
5. See count of `1 Thread Reply`

**Expected behavior**
Thread replies should show a count of `2`

**Screenshots**
<img width="390" alt="Screen Shot 2021-11-16 at 15 18 35" src="https://user-images.githubusercontent.com/7506979/142075182-12e98b6f-90f8-4550-8794-5c2c7f76fe09.png">
<img width="162" alt="Screen Shot 2021-11-16 at 15 18 40" src="https://user-images.githubusercontent.com/7506979/142075187-54335f08-fb85-4045-8bb6-6cdeb4cfe4e3.png">

gz#16790

**Comment by madsroskar** [comment]
Does this stay this way if you reload the message list? Initial testing on my end doesn't reproduce this issue, is anything logged to your console while going through the reproduction steps you've shared?

**Comment by lucaswhitman** [comment]
Hey @madsroskar, no changes when I reload (even the entire app). Nothing in the console I don't expect.

**Comment by lucaswhitman** [comment]
If it helps I'm also seeing this in the dashboard explorer:

<img width="502" alt="Screen Shot 2021-11-16 at 15 51 29" src="https://user-images.githubusercontent.com/7506979/142078963-9774a4c0-c16e-47a7-9b37-aa9349b619ff.png">

The giphy response itself seems to be labeled as a system message (we've not changed how these are delivered)

<img width="475" alt="Screen Shot 2021-11-16 at 15 51 36" src="https://user-images.githubusercontent.com/7506979/142079020-08500c83-5e2a-446b-a575-d60657063542.png">

**Comment by madsroskar** [comment]
It's odd that it doesn't have the `reply` message type, or `command: giphy` set. Afaik, we don't send anything as system messages from the SDK out of the box, so I'm a bit unsure how this would happen. 

Could you send us an email at <support@getstream.io> with the app ID or API key used for your application?

**Comment by lucaswhitman** [comment]
@madsroskar sure can. Actually, I may be wrong on that second screen shot. I'm not seeing the giphy in the set of messages, at least not at first glance. I think that system message may be a red herring.

**Comment by madsroskar** [comment]
It doesn't seem like the message containing the giphy has been sent at all, but not being able to reproduce the issue makes it a bit tricky to figure out why the giphy seemingly gets rendered as if it's sent.

Are you using any custom components related to messages or attachments at all? Or a custom Giphy component?

**Comment by lucaswhitman** [comment]
@madsroskar we've got a custom `Card` component that renders different message types based on our own custom attachments. But Giphy travels down to a traditional `Card` and so the render should be all Stream code.

**Comment by vishalnarkhede** [comment]
Hey @lucaswhitman we are still investigating this on our end. It seems like there could be some issue with channel configuration, but we will get back to you once we have more information from our backend team

**Comment by lucaswhitman** [comment]
@vishalnarkhede thanks, just let us know. It's blocking a feature for us so I'm happy to provide any more info you need.

**Comment by lucaswhitman** [comment]
@vishalnarkhede @madsroskar any updates here?

**Comment by madsroskar** [comment]
Hi @lucaswhitman - I don't yet have an update unfortunately. I've requested some help looking into this from our backend developers, and pinged them for an update now. I'll get back to you once I have an update.

Thank you for your patience with this, I hope we'll have an answer/know what's going on here asap.

**Comment by madsroskar** [comment]
It looks like the backend team is getting closer to finding the root cause of this, which is promising. I don't yet know how quickly they'll be able to have a fix for it in place yet, but I'll check back in here tomorrow at the latest with the current status of this.

**Comment by lucaswhitman** [comment]
Great. We appreciate the updates @madsroskar

**Comment by lucaswhitman** [comment]
@madsroskar is there a backend issue I can watch?

**Comment by madsroskar** [comment]
I can only apologize for not coming back with an update when I said I would, thank you for the ping here. Unfortunately there's only an internal issue for it, but I'll ask for an update regarding this.

**Comment by madsroskar** [comment]
Hi again @lucaswhitman! This should be resolved, and my test case to reproduces it seems to confirm it. There shouldn't be anything you need to do on your end.

I'll close the issue now, but please test it in your application when you get the time, and feel free to update in this issue if you still experience the issue, then I'll reopen it. :)

**Comment by lucaswhitman** [comment]
Thanks @madsroskar, we'll push our internal issue to QA and let you know if there's anything to report.

**Comment by lucaswhitman** [comment]
@madsroskar our QA is still seeing this issue. There's no updates we need on our end?

**Comment by lucaswhitman** [comment]
Repro steps from our QA:

> If a user completes a search on giphy within a thread, cancels, completes new search, and then sends a selection to the channel the thread reply will increase by two for the one reply. 
For each cancel and new search an additional count is added to the thread replies.

**Comment by madsroskar** [comment]
Thanks for getting back to me with this feedback, I'll reopen the issue so we can get to the bottom of this.
Does this also happen in a new channel created after I wrote [this comment](https://github.com/GetStream/stream-chat-react-native/issues/1004#issuecomment-990904670)?

Thanks for sharing the steps for a repro, I'll see if I can reproduce it on my end as well. 

> There's no updates we need on our end?

I'll double-check this with our backend engineers, if it's not happening on a new channel, it could be that we need to clean up the failed giphy messages from before the deployment was made on Friday, but at this point, that's just a guess on my end till I know more.

If there are other odd and/or similar behaviors that you and your team come across, it's much appreciated if you continue sharing them with us in this issue.

For internal reference: CRNS-502 is added to our current spring to follow up on this.

**Comment by lucaswhitman** [comment]
@madsroskar I'm not sure about if it's a new channel. Regardless, that fix wouldn't work for our existing users so... It is happening on new threads created since that comment.

**Comment by madsroskar** [comment]
Hi again, @lucaswhitman.

The issue as described with the reproduction steps from your QA seems to have a different root cause that we weren't aware of, which is why the fix deployed on Friday didn't cover that. The message sent to our backend to initialize the giphy search seems to be counted as a response.

I'm looking into a fix for this, and will get back to you as soon as I know more.

**Comment by lucaswhitman** [comment]
@madsroskar great, thanks for reopening.

**Comment by madsroskar** [comment]
Hi again, @lucaswhitman!

This seems to be fixed when I'm testing on my end, would you be able to see if you still experience this in your applicaiton?

**Comment by lucaswhitman** [comment]
Hey @madsroskar, our staff is on holiday but I'll throw the internal ticket back to our QA when we get back. Feel free to close and I'll comment here on the resolution.

**Comment by lucaswhitman** [comment]
Well, our QA kicked it back again on our end.

> If a user completes a search on giphy within a thread, cancels, completes new search, and then sends a selection to the channel the thread reply will increase by two for the one reply. For each cancel and new search an additional count is added to the thread replies. Confirmed this is still occurring in the latest version.

Worth noting we also just updated to the latest version of this lib and `stream-chat-js` too.

**Comment by madsroskar** [comment]
> Confirmed this is still occurring in the latest version.

I'm sorry to hear that, that's not great. I'm reopening this, I'll get back to you with any info I get as soon as I have it.

**Comment by madsroskar** [comment]
Hi again Lucas, a cache issue has been deployed this morning that should address this (again), and my tests confirm that it works as expected on my end. Would you be able to see if it is resolved on your end as well when you get the chance?

**Comment by lucaswhitman** [comment]
@madsroskar sorry, we're still seeing it... 😞

**Comment by madsroskar** [comment]
That's not good. :( Thanks for the update, I'll raise it internally again.

**Comment by lucaswhitman** [comment]
@madsroskar?

**Comment by madsroskar** [comment]
Hi again Lucas. I'm terribly sorry for the lack of response here. I just tested this, and it seems like the giphys are being counted properly at the moment. Are you still experiencing issues with this?

**Comment by lucaswhitman** [comment]
I'll send it back to our QA again, but every time I have it's still experiencing the same issue. I'll get back to you soon.

**Comment by madsroskar** [comment]
I understand - and I'm sorry for the extra frustration about that. I've tried to test it out myself to reproduce the issues as described before but at the moment those seem to work fine after the last time I talked to our backend team about this. If your QA still encounters issues - I'd be very thankful for any information and/or steps to reproduce that are available.

If you still encounter issues about this, could I maybe suggest we get on a call to dig into this together? If so, I'll send you an email to schedule a call at a time that would work for you

**Comment by lucaswhitman** [comment]
Here's a replay, the area that the issue occurs in is pretty generic Stream UI.

https://user-images.githubusercontent.com/7506979/156616623-b4daaaff-40a7-4c50-a8fa-cc49c51c0e8f.MP4

**Comment by vanGalilea** [comment]
@lucaswhitman thanks for reaching out, is this issue still relevant?

**Comment by lucaswhitman** [comment]
@vanGalilea it would have been great to have, but we've moved on to other projects not using Stream.

**Comment by khushal87** [comment]
This seems to work fine:

https://user-images.githubusercontent.com/39884168/169955536-2acc5db2-a642-4ade-a34a-a1693902e1c7.mov

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1004?planning-poker) with ZenHub @Enigma-I-am @khushal87 @madsroskar @santhoshvai @vishalnarkhede

**Comment by vanGalilea** [comment]
Let's also check internally if somebody experiences something similar
