### ISSUE TITLE
[Android][v4] Bottom Sheet randomly appearing

### ISSUE THREAD

**Issue by robrechtme** [GetStream/stream-chat-react-native#1179]
**Describe the bug**
On Android, the bottom sheet from the Attachment picker is sometimes appearing when opening/closing the keyboard or changing between keyboards. This issue occurred since the v4 upgrade. 

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): **4.1.0**
- react-native or expo version: **RN 0.67.2**
- Device/Emulator (android/ios) and OS version: **Multiple Android devices**

**To Reproduce**

1. Wrapp app with `OverlayProvider`
2. Open/Close the keyboard on multiple types of input fields
3. The issue does not appear every time

**Expected behavior**
No bottom sheet is shown

**Additional context**

- We do have `android:windowSoftInputMode="adjustResize"` in the manifest, maybe this causes the issue.

**Screenshots**
<img height="600" src="https://user-images.githubusercontent.com/24371353/156593665-c5b7634c-f1da-4a47-bcc1-c45c9253342e.gif" />

gz#20206

**Comment by mattlennon3** [comment]
We are seeing this too, android only, fresh integration of Stream components.

![Screenshot_20220406-123124_ Dev  Mana](https://user-images.githubusercontent.com/9389496/161967281-b7bf2974-dbbc-49e6-8e0f-5c1e65da3cf2.jpg)

**Details**
"stream-chat-react-native": "4.3.0",
"react-native": "0.66.4",

Devices:
Pixel 6, Samsung S10.

You can get rid of the drawer by pulling it up and then down, it will then disappear and work as expected for the rest of the app session.

**Additional context**
We also have `android:windowSoftInputMode="adjustResize"` set, like @robrechtme has.

**Comment by GregAtFramework** [comment]
We've been experiencing this too on Android. It's frustratingly intermittent. But when it does occur, it obscures our app's primary navigation (tabs along the bottom of the screen).

"stream-chat-react-native": "4.3.0",
"react-native": "0.66.4",

**Comment by denizmersinlioglu** [comment]
@vishalnarkhede this problem happens in iOS too, FYI ✋

**Comment by mattlennon3** [comment]
@denizmersinlioglu can you provide some basic info about your ios build? 🙄

**Comment by vishalnarkhede** [comment]
Is it possible for anyone to share a minimal example app with us, where we can reproduce these issue?

**Comment by mattlennon3** [comment]
Hi @vishalnarkhede, I don't have time to make an example app for you. But I am happy to share my screen and you can take a look at some of the code behind our app if you like?

**Comment by vanGalilea** [comment]
@mattlennon3 are you still facing this issue?

**Comment by mattlennon3** [comment]
Hi @vanGalilea, yeah we're still seeing this in our dev & prod apps.
We've not been able to pin down the exact trigger in our day to day use. I most often see it on first launch, but not always!

**Comment by santhoshvai** [comment]
Hey @GregAtFramework, do you have `android:windowSoftInputMode="adjustResize"` in the manifest too?

**Comment by GregAtFramework** [comment]
@santhoshvai  Yes we do. Though I'm fairly confident it's not something we've set explicitly ourselves - I believe it's part of Expo's default configuration.

**Comment by santhoshvai** [comment]
@GregAtFramework Thank you. As you say this is the default input mode in the default RN template.

I believe this is related to the v4 version of the bottom sheet library:
https://github.com/gorhom/react-native-bottom-sheet/issues/761

If you would downgrade to 3.6.6 it might fix the issue. But I haven't been able to verify this as I couldn't reproduce this issue in the android devices we have here.

**Comment by vanGalilea** [comment]
I could not reproduce this. Can someone please share a repo where this issue occurs in?

**Comment by mattlennon3** [comment]
Hi @vanGalilea. I attempted to make a repo to replicate this yesterday. Unfortunately I couldn't reproduce the same bug.
We can now pretty reliably replicate this problem by jumping focus from one input to another. I'll attach a video.

This is a basic screen (not within a modal as it might appear) and we are using `react-hook-form`, which I don't think is part of the problem.
The logic of this page works kind of like this:
"show the title and a selection of other properties to set below"
"if one of the below properties is selected, hide the rest of the screen and only show the input for that property, focus the input"
We do see this drawer pop up on launch of the app sometimes. So perhaps there is an input being focused for a split second (e.g login/signup page).
Not sure how helpful that is, but it's all we have on our end!

https://user-images.githubusercontent.com/9389496/168796621-e4df9e45-8b86-4979-a85a-8432b084bae0.mp4

**Comment by rajkapoordev** [comment]
Hello @robrechtme @mattlennon3 @santhoshvai @vishalnarkhede 

I have fixed this issue but it is not a proper solution.
I have added conditions before BottomSheet to render.
Also added `keyExtractor = item.asset.uri+  Date.now()` because it throwing same key warning.


```
{selectedPicker === 'images' &&  (
    <BottomSheet
    key={'hello'}
    containerHeight={fullScreenHeight}
    enablePanDownToClose={true}
    handleComponent={
      /**
       * using `null` here instead of `style={{ opacity: photoError ? 0 : 1 }}`
       * as opacity is not an allowed style
       */
      photoError ? null : AttachmentPickerBottomSheetHandle
    }
    handleHeight={handleHeight}
    index={-1}
    onChange={(index: number) => setCurrentIndex(index)}
    ref={ref}
    snapPoints={snapPoints}
  >
    <BottomSheetFlatList
      contentContainerStyle={[
        styles.container,
        { backgroundColor: white },
        bottomSheetContentContainer,
        { opacity: photoError ? 0 : 1 },
      ]}
      data={selectedPhotos}
      keyExtractor={(item) => item.asset.uri+  Date.now()}
      numColumns={numberOfAttachmentPickerImageColumns ?? 3}
      onEndReached={getMorePhotos}
      renderItem={renderImage}
    />
  </BottomSheet>
)}

```

**Comment by vishalnarkhede** [comment]
@mattlennon3 @robrechtme We have published a beta version `v4.5.1-beta.1` where this issue should be fixed. Could you please upgrade/test and confirm?

**Comment by santhoshvai** [comment]
I have reponed this, as it seems to be not totally fixed but still happening

**Comment by vanGalilea** [comment]
@GregAtFramework and @mattlennon3 Thanks for reaching out!
This one is super difficult to pinpoint. We would like to ask you to share a minimalistic repo where the problem is reproduced.
The fastest way to achieve this is with the following command to create a new RN project with Stream chat in it:

`npx react-native init MyApp --template stream-chat-react-native-template`

Please then share a Github repo with us, where we can explore the issue ourselves.

**Comment by isaac-computer** [comment]
I'm also seeing this on iOS with version 4.7.3

**Comment by isaac-computer** [comment]
@vanGalilea I went deep on this one today because in our app, for whatever reason, this sheet was appearing every single time you put the app in the background. It took a few hours but I was able to pin it down! It's because of this issue noted in the BottomSheet package: https://github.com/gorhom/react-native-bottom-sheet/pull/919. If you update to a newer version after this PR was merged it's fixed. 

For now I used patch-package cc @mattlennon3

**Comment by santhoshvai** [comment]
Hey @isaac-computer, many thanks for investigating this and finding the possible PR that fixes this. The version in which the fix has been released was v4.1.6 of the bottom sheet package. 

@mattlennon3 Could you please update the bottom sheet package to v4.1.6 or later and update us if you can still get the issue. We are not able to reproduce this on our end due to it being a race condition.

**Comment by santhoshvai** [comment]
I am closing this issue, as we believe that this should be fixed in version 4.1.6 or later of the [react-native-bottom-sheet](https://github.com/gorhom/react-native-bottom-sheet) library.

**Comment by GregAtFramework** [comment]
@santhoshvai Currently stream-chat-react-native-core [depends on](https://github.com/GetStream/stream-chat-react-native/blob/develop/package/package.json) `"@gorhom/bottom-sheet": 4.1.5`. Could you update that dependency please?

**Comment by santhoshvai** [comment]
@GregAtFramework Thanks a lot. Good point will do in the upcoming release

**Comment by GregAtFramework** [comment]
We upgraded to 4.10.0 (and bottom-sheet 4.4.2) and unfortunately my colleague and I are still seeing the Android issue. (Perhaps unsurprisingly, as the bottom-sheet issue specifically references iOS).

I would love to try to create a minimalistic repo, but I don't know when I will find the time to try to put that together.

**Comment by codingwaysarg** [comment]
Still happening on:

"expo": "46.0.6",
"stream-chat-expo": "4.14.0",
"react-native": "0.69.4",
"@gorhom/bottom-sheet": "4.4.3"

I've tried many things without success. Any thoughts?

Thanks.

**Comment by GregAtFramework** [comment]
I've given this fix a go: https://github.com/GetStream/stream-chat-react-native/issues/1283#issuecomment-1230607471 - a patch-package change to `AttachmentPicker.tsx`.


It's early days, but we haven't seen the issue since doing that.

**Comment by neopit** [comment]
I don't understand all the code but this area seems weird and maybe the issue comes from here.
https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/AttachmentPicker/AttachmentPicker.tsx#L396

There is already a comment about a race condition for closing the BottomSheet.

Why is there a 150ms timeout? What happens if we put a 300?
And why it is really needed?

Is there any relation with the snappoint change? Here https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/AttachmentPicker/AttachmentPicker.tsx#L500

**Comment by santhoshvai** [comment]
Hi @GregAtFramework @codingwaysarg @mattlennon3 @isaac-computer @denizmersinlioglu @robrechtme

We have published a new beta version  [v5.4.2-beta.2](https://github.com/GetStream/stream-chat-react-native/compare/v5.4.1...v5.4.2-beta.2) that aims to fix this issue. Could you please upgrade to this version and remove the patch package to `AttachmentPicker.tsx` (if any) and see if it's fixed.

I believe that this happens due to a race condition in the bottomsheet library. I was able to create a reproducible scenario and fix it there. But we want your feedback to finally confirm if this bug has been squashed out. It would be immensly helpful if you can test and report to us.

**Comment by neopit** [comment]
On our side, we have tested this beta version with the fix and it fixes the bug. We are not seeing this white bottom sheet.
Maybe you are waiting for more feedback for other developers but do you have an idea when this fix can be available in the main branch?

**Comment by santhoshvai** [comment]
Hey @neopit, many thanks for testing it and the feedback; very happy to hear that this seems to fix it. It should be available in the main branch and released in about 5 days if there is no negative feedback in the meantime.

**Comment by neopit** [comment]
@santhoshvai Is the fix merged?

**Comment by mrwatts88** [comment]
Still seeing the the issue in v5.4.2-beta.2

**Comment by neopit** [comment]
We've bumped our app with the 5.4.1, tested, and run our E2E. We did not see the bug anymore.

But seeing this message above from, mrwatts88, .... hmmmm, I am stressed now :-)

**Comment by sraut1** [comment]
This isue still exist on 5.34.0

**Comment by sraut1** [comment]
@santhoshvai @vanGalilea This issue occurs on intermittently on keyboard hide and also regularly when app is switched from portrait to landscape. here is the video

To Reproduce
Steps to reproduce the behavior:

Play a YouTube video using the YouTubePlayer component (react-native-youtube-iframe).
Switch the video to fullscreen mode.
Rotate the device to landscape orientation while in fullscreen mode.
Rotate back to portrait mode
Exit fullscreen mode.

https://github.com/user-attachments/assets/86a8ba03-4729-4245-990c-df9bc0a42447
