### ISSUE TITLE
[🐛] White ghost modal issue still exist

### ISSUE THREAD

**Issue by sraut1** [GetStream/stream-chat-react-native#2655]
## Issue

This issue occurs on intermittently on keyboard hide and also regularly when app is switched from portrait to landscape. here is the video

https://github.com/user-attachments/assets/41aeb257-5102-4198-a0d7-ba3014d0ede4

<img width="262" alt="Screenshot 2024-09-05 at 10 35 30 AM" src="https://github.com/user-attachments/assets/6d899767-45da-4561-900f-d725210b7237">

### Steps to reproduce

1. Play a YouTube video using the YouTubePlayer component (react-native-youtube-iframe).
2. Switch the video to fullscreen mode.
3. Rotate the device to landscape orientation while in fullscreen mode.
4. Rotate back to portrait mode
5. Exit fullscreen mode.

## Project Related Information

Device: iPhone 15 Pro or Galaxy S23
OS + version: iOS 17.4
Expo verison 51.0.24
stream-chat-expo: 5.36.1
stream-chat-react-native: 5.34.0
gorhom/bottom-sheet: 4.6.4 via stream-chat-react-native-core

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by sraut1** [comment]
@santhoshvai @vanGalilea

**Comment by sraut1** [comment]
@khushal87 I saw check was added in latest version to open AttachmentPicker. but still AttachmentPicker is getting opened randomly in the app:

`{isImageMediaLibraryAvailable() ? (
                  <AttachmentPicker ref={bottomSheetRef} {...attachmentPickerProps} />
                ) : null}`

`isImageMediaLibraryAvailable()` is always true

**Comment by khushal87** [comment]
Hey @sraut1, the `isImageMediaLibraryAvailable()` is true because the cameraroll dependency is there for you in your project. We also introduced an option to switch to a native image picker, so maybe you can try that out.

Here is the guide - https://getstream.io/chat/docs/sdk/reactnative/guides/native-image-picker/

**Comment by sraut1** [comment]
Hey Thanks for the response @khushal87 we do allow camera/gallery access in the app but through expo-camera, we are not using camera roll for chat functionality though. but even though someone is using react-native-camera-roll,  AttachmentPicker  popping randomly in the app is buggy. any suggestion?

**Comment by khushal87** [comment]
Yeah, for the expo, it should be expo-media-library for your case. About the issue with the attachment picker, we will triage it and get back to you once it's reproducible. Thanks 😄

**Comment by sraut1** [comment]
Thanks @khushal87 removing `expo-media-library` resolves the issue as `isImageMediaLibraryAvailable()` returns false.

**Comment by khushal87** [comment]
Fixed with #2687

**Comment by arekkubaczkowski** [comment]
well, this issue still exist on the latest (5.39.1) version.
this happens after orientation change.

![image](https://github.com/user-attachments/assets/20fd25e3-4b9a-4cf8-9b21-78a7ea83fa96)

**Comment by arekkubaczkowski** [comment]
should we reopen it?

**Comment by khushal87** [comment]
Hey @arekkubaczkowski, I don't see this problem when using the keyboard or the image gallery on the latest version when I change orientation as well. 

https://github.com/user-attachments/assets/b7414dbb-a78b-4bfb-b5d6-44874c5ad221

**Comment by arekkubaczkowski** [comment]
well, on your video the bottom sheet appears for a moment, I believe this is not a desired approach, in my case it just shows for a bit longer.

**Comment by khushal87** [comment]
Yes, the flickering is a well-known issue for bottom sheet package - https://github.com/gorhom/react-native-bottom-sheet/issues/516 and I don't see there's a fix yet.
