### ISSUE TITLE
Not receiving messages after app comes from background

### ISSUE THREAD

**Issue by bojans1005** [GetStream/stream-chat-react-native#494]
**Describe the bug**
When the app comes from background after a long time, user is not receiving the messages anymore

**Dev environment info:**

- stream-chat-react-native: 2.1.1
- react-native: 0.62.2
- Device/Emulator: ios emulator

**To Reproduce**

1. Chat working fine with other user
2. Open another app or force the app to backgorund
3. After some time, open the app again
4. The other user sends message
5. Not receiving any message

**Expected behavior**
I expect web socket refreshed automatically when app comes to foreground, but it doesn't seem to be working

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/8812'>Zendesk ticket #8812</a>:<br><br>Hi,

Thanks for reaching out. The web socket is automatically disconnected after a set amount of time when you background the App.

Please reference this doc on web socket behavior and set up related to when the App is backgrounded - https://github.com/GetStream/stream-chat-react-native/wiki/Cookbook-(2.x.x)#caveats

Please let me know if you have any further questions here!

Best,
Ryan

**Comment by bojans1005** [comment]
I also tried that
```
if (
  appState.current.match(/inactive|background/) &&
  nextAppState === 'active'
) {
  await chatClient._setupConnection();
} else if (
  nextAppState.match(/inactive|background/) &&
  appState.current === 'active'
) {
  await chatClient.wsConnection.disconnect();
}
```

It seems `chatClient.wsConnection.disconnect();` is working as I don't receive messages immediately after app goes to background, but `chatClient._setupConnection();` is not working

If I have these code disabled, I get messages if I return to the app from background within 10~15 seconds, but with this enabled, I don't receive any messages immediately

**Comment by bojans1005** [comment]
@shodgetts do you have any idea on this?

**Comment by vishalnarkhede** [comment]
Hey @bojans1005 just to confirm something regarding the code that you shared above - both if and else condition are same. Did you try fixing it?

**Comment by bojans1005** [comment]
@vishalnarkhede the conditions are not same, first part is for app coming from background to active, `else if` part is for app going to background from `active` status

**Comment by vishalnarkhede** [comment]
@bojans1005 pardon me, I misread the code at first. Thats why I deleted my previous comment :)

**Comment by bojans1005** [comment]
@vishalnarkhede no problem

**Comment by vishalnarkhede** [comment]
@bojans1005 Could you please share rest of the code as well? Around StreamChat and chat components

**Comment by bojans1005** [comment]
@vishalnarkhede 
```
const HomeChat = () => {
  const chatClient = ChatClientService.getClient();

  const [channel, setChannel] = useState();
  const [isReady, setIsReady] = useState(false);
  const { state: authState } = useContext(AuthContext);

  useEffect(() => {
    getChannel();
  }, []);

  const getChannel = () => {
    const _channel = chatClient.channel('messaging', {
      members: [xxxx],
    });
    setChannel(_channel);
    setIsReady(true);
  };

  if (!isReady) {
    return null;
  }

  return (
    xxx
      <Chat client={chatClient} style={streamChatTheme}>
        <Channel
          client={chatClient}
          channel={channel}
          // disableKeyboardCompatibleView={true}
          KeyboardCompatibleView={CustomKeyboardCompatibleView}>
          <MessageList Message={Message} />
          <MessageInput Input={InputBox} />
        </Channel>
      </Chat>
   xxx
  );
};

export default HomeChat;
```

**Comment by bojans1005** [comment]
@vishalnarkhede is there any way we can get real time support?
we are very tight in timeline and will have to cancel subscription and look for other solutions if this can't be solved soon

**Comment by AustinWood** [comment]
+1 fixing this is critical to using StreamChat for our business

**Comment by vishalnarkhede** [comment]
> @vishalnarkhede is there any way we can get real time support?
> we are very tight in timeline and will have to cancel subscription and look for other solutions if this can't be solved soon

@bojans1005 Please get in touch with support@getstream.io

**Comment by bojans1005** [comment]
@vishalnarkhede thanks

**Comment by vishalnarkhede** [comment]
@bojans1005 could you please also share ChatClientService?

**Comment by bojans1005** [comment]
```
export default {
  client: null,
  setClient: client => (this.client = client),
  getClient: () => this.client,
};
```
This is what I got from slack clone repo

**Comment by bojans1005** [comment]
Here is the part where I create chat client on App.js

```
useEffect(() => {
    
    AppState.addEventListener('change', _handleAppStateChange);

    const client = new StreamChat(appConfig.getstream.apiKey, {
      timeout: 10000,
    });
    ChatClientService.setClient(client);

    return () => {
      AppState.removeEventListener('change', _handleAppStateChange);
    };
  }, []);
```

**Comment by vishalnarkhede** [comment]
@bojans1005 IWhere is the `client.setUser` call?

**Comment by bojans1005** [comment]
@vishalnarkhede 
That is done when login succeeds

```
const chatClient = ChatClientService.getClient();
    chatClient.disconnect();
    chatClient.setUser(
      {
        id: `${user.id}`,
        name: user?.fullName ?? 'User',
      },
      user.getstreamToken,
    );

    chatClient.addDevice(
      pushToken.token,
      pushToken.os === 'ios' ? 'apn' : 'firebase',
    );
```

**Comment by bojans1005** [comment]
@vishalnarkhede 
can this be related to https://github.com/GetStream/stream-chat-react-native/issues/451#issuecomment-744475053?
or is it already resolved?

**Comment by vishalnarkhede** [comment]
@bojans1005 

> can this be related to #451 (comment)?

This was recently fixed within stream-chat package.

One of the common reasons that we have seen around the issue that you are facing is - having multiple websocket connections due to some wrong integration. We have published `stream-chat@2.12.0` which introduces singleton pattern on client.

So I would recommend you to upgrade to stream-chat@2.12.0 and initiate the client as following:

```js
import { StreamChat } from 'stream-chat';

const chatClient = StreamChat.getInstance('api_key');
await chatClient.connectUser(
  {
    id: `${user.id}`,
    name: user?.fullName ?? 'User',
  },
  user.getstreamToken,
);
```

And let us know if that fixes issue for you. Otherwise we can dig deeper then :)

**Comment by bojans1005** [comment]
@vishalnarkhede 
it still does not work
I guess socket connection is still alive as I get user is typing message on web app, when I am typing on mobile, but mobile socket does not receive message events somehow

**Comment by bojans1005** [comment]
@vishalnarkhede 
number of users online becomes 1 (from 2) when I call `chatClient.wsConnection.disconnect();` but does not get updated back to 2 when I call `chatClient._setupConnection();` 
I wonder how I get `user is typing` message even when online user count is 1 (web app user only)

**Comment by vishalnarkhede** [comment]
Hey @bojans1005 could you send me a copy of logs, when you call `_setupConnection`? You need to use logger available on js client - https://github.com/GetStream/stream-chat-js/blob/master/docs/logging.md#logging

```js
const client = StreamChat.getInstance('api_key', {
    logger: (logLevel, message, extraData) => {
        if (extraData.tags.indexOf('connection') > -1) {
            console.log(message); // or any logging tool that you are using e.g. reactotron
        }
    },
  });
```

**Comment by bojans1005** [comment]
@vishalnarkhede 
```
connection:connect() - Established ws connection with healthcheck: [object Object]
```

It seems socket receives the message also

```
connection:onmessage() - onmessage callback
```

But UI is not refreshing even when socket receives message

**Comment by bojans1005** [comment]
@vishalnarkhede I found one possible issue causing this
Initially when I get channel  chatClient has one active channel with `id` value undefined

![image](https://user-images.githubusercontent.com/67975929/106414411-41ff7780-6498-11eb-9293-2ad5be69e3a5.png)

But after some time, I find that there are 2 channels exactly same with different keys on activeChannels

![image](https://user-images.githubusercontent.com/67975929/106414501-7115e900-6498-11eb-8834-7e2217b1f862.png)

**Comment by bojans1005** [comment]
@vishalnarkhede I can see this is happening at some point when this api call is made by chat client
```
curl -X POST  -H "accept:application/json, text/plain, */*" -H "content-type:application/json;charset=utf-8" -H "authorization:xxxxxxxx" -H "stream-auth-type:jwt" -H "x-stream-client:stream-chat-react-native-ios-2.1.1" https://chat-us-east-1.stream-io-api.com/channels/messaging/query?user_id=15&api_key=xxxxxxx&connection_id=xxxxxxx -d '{"data":{"members":["15","admin"]},"state":true,"watch":true,"presence":false}'
```

**Comment by vishalnarkhede** [comment]
Hey @bojans1005 , thanks for this info. I am looking into it now

**Comment by vishalnarkhede** [comment]
@bojans1005 I have published a patch - v2.2.1. Can you please upgrade and check?

**Comment by bojans1005** [comment]
@vishalnarkhede I tested with new version but it's still same

![image](https://user-images.githubusercontent.com/67975929/106813109-4dcb8380-66bc-11eb-8b44-c570efc09926.png)

**Comment by vishalnarkhede** [comment]
@bojans1005 This is a different thing, just needs a bit of cleanup in js client during recovery, but its not really a concern here. Are you still not able to see updated channels on UI?

**Comment by bojans1005** [comment]
@vishalnarkhede I still don't receive messages when I come from background
In streamchat console, I can see messages arriving, but the UI is not being updated, I thought because there are multiple active channels, maybe the message is sent to the other channel

**Comment by bojans1005** [comment]
![image](https://user-images.githubusercontent.com/67975929/107009795-3b973580-67e1-11eb-914f-0b7b9bb1c1d6.png)
This is log when I go to background and come back, it seems connection is re-established but ui is not being updated

Can this be related to the multiple channels created?

**Comment by bojans1005** [comment]
@vishalnarkhede I made some changes on stream chat typescript code, how can I build it and test it?

**Comment by bojans1005** [comment]
@vishalnarkhede I made a PR on `stream-chat-js` library, can you please check it?
https://github.com/GetStream/stream-chat-js/pull/610

**Comment by virdesai** [comment]
@bojans1005 if you pull these SDKs locally you can change the package.json version number to `"stream-chat": "link:../path/to/stream-chat-js-SDK"` and for your app you can change the `"stream-chat-react-native": "link:../path/to/stream-chat-react-native-SDK"`

**Comment by virdesai** [comment]
@bojans1005 if you can get this local linking setup for testing, try to add this to `src/components/ChannelList/hooks/usePaginatedChannels.ts` and see if it fixes the problem
```
  const clientConnectionID = client.connectionID;
  useEffect(() => {
    channels.map((channel) => channel.watch());
  }, [clientConnectionID]);
```

**Comment by vishalnarkhede** [comment]
@bojans1005 Do you only use Channel component or also use ChannelList component?

**Comment by bojans1005** [comment]
@vishalnarkhede I only use channel component but not channel list
our business logic for chat is admin vs users, and not allow chat users vs users

**Comment by vishalnarkhede** [comment]
@bojans1005 thanks for the response. I can see the issue now!!

**Comment by bojans1005** [comment]
@vishalnarkhede did you check my PR on `stream-chat-js` repo?
That did not completely solved my issue, but at least avoid multi channels getting created
I found that `user_id` was `undefined` on query response

https://github.com/GetStream/stream-chat-js/pull/610/files#diff-5b3bc0170c6b446a9fc0ef2adfe40432447d1716c48b63cdf212cfa96a77b20bR1254

**Comment by vishalnarkhede** [comment]
@bojans1005 Could you please try v2.2.2 of stream-chat-react-native and see if that fixes the issue for you?

**Comment by bojans1005** [comment]
@vishalnarkhede it works now, thanks for your help

**Comment by vishalnarkhede** [comment]
Glad to hear that !! :)

**Comment by bojans1005** [comment]
@vishalnarkhede please check my PR for stream chat library
https://github.com/GetStream/stream-chat-js/pull/610
That might also help preventing multiple channels created when creating channel from member list

**Comment by mikevercoelen** [comment]
@vishalnarkhede even with the latest version I'm still having issues, something is broken and it's pretty bad.

What's happening is:

Editing / reactions are working fine until the app is hidden, so no longer in focus, and wait for about 1 / 2 minutes and then open the app again and start editing / posting reactions.

The changes ARE being made, but they aren't updated in the UI.

Checkout this video:

https://user-images.githubusercontent.com/3009836/107335932-7eb01c00-6af3-11eb-9226-4904431cdce1.mp4

These are the versions I'm on:

```
"stream-chat": "^2.12.0",
"stream-chat-react-native": "^2.2.2",
"react-native": "0.63.4",
```

Also creating an issue for this...
