### ISSUE TITLE
Testing with Jest - SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by jaimebiernaski** [GetStream/stream-chat-react-native#508]
**Describe the bug**

It is not possible to test using  `Stream` with `Expo + Jest + React Native Testing Library`, even on the tutorial example, due the following error:

    /.../node_modules/stream-chat-expo/src/index.js:1
    import { registerNativeHandlers } from 'stream-chat-react-native-core';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

**Dev environment info (please complete/provide the following information):**

All the packages were installed according to the oficial documentation & stream tutorials

```json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo",
    "setupFilesAfterEnv": [
      "@testing-library/jest-native/extend-expect"
    ]
  },
  "dependencies": {
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "5.9.7",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",
    "expo": "~40.0.0",
    "expo-document-picker": "~8.4.1",
    "expo-image-picker": "~9.2.0",
    "expo-permissions": "~10.0.0",
    "expo-status-bar": "~1.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-reanimated": "~1.13.0",
    "react-native-safe-area-context": "3.1.9",
    "react-native-screens": "~2.15.2",
    "react-native-web": "~0.13.12",
    "stream-chat": "^2.12.0",
    "stream-chat-expo": "^2.1.4"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "@testing-library/jest-native": "^3.4.3",
    "@testing-library/react-native": "^7.1.0",
    "jest-expo": "^40.0.2"
  },
  "private": true
}

```

**To Reproduce**

Repo with the [example](https://gitlab.com/jaimebiernaski/stream-jest-error) code.

1. Create the example aconding to the [react-native-chat](https://getstream.io/chat/react-native-chat/tutorial/) tutorial
2. Install the Jest according to the [Expo documentation](https://docs.expo.io/guides/testing-with-jest/)
3. Install React Native Testing Library according to the [oficial documentation](https://callstack.github.io/react-native-testing-library/docs/getting-started/)
4. Create an simple test file `App.test.js` with the following content:

```javascript
import React from 'react';
import { render } from '@testing-library/react-native';
import App from './App';

test('render', () => {
  const { getByTestId } = render(<App />);
  expect(getByTestId('app')).toBeTruthy();
});

````

5. Run the test: `$ yarn test`
6. Get the error:
 
  > $ jest
   FAIL  ./App.test.js
    ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /.../node_modules/stream-chat-expo/src/index.js:1
    import { registerNativeHandlers } from 'stream-chat-react-native-core';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
        at compileFunction (<anonymous>)

      2 | import { View, SafeAreaView } from 'react-native';
      3 | import { StreamChat } from 'stream-chat';
    > 4 | import { Chat, Channel, MessageList, MessageInput } from 'stream-chat-expo';
        | ^
      5 | 
      6 | const chatClient = new StreamChat('f8wwud5et5jd');
      7 | const userToken =

      at Runtime._execModule (node_modules/jest-runtime/build/index.js:1157:58)
      at Object.<anonymous> (App.js:4:1)

**Expected behavior**
The test runs with no problem.

gz#9075

**Comment by klougod** [comment]
Same thing happening over here, would help a lot a solution for this!

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/9075'>Zendesk ticket #9075</a>:<br><br>Hi,

Thanks for reaching out. I am not as familiar with JEST, so I may need to redirect this internally, but looking at this error message it looks like there is quite a bit of information back from JEST. It also looks like you have import errors and there isn't a userToken present. Are you able to remedy these issues?

Best,
Ryan

**Comment by jaimebiernaski** [comment]
This exact same error occurs when testing our production app, with all the required setup. This erro impacts just the testing process, not the app itself.

**Comment by virdesai** [comment]
@jaimebiernaski could you try to add this to your jest setup 
`
    "transformIgnorePatterns": [
      "node_modules/(?!react-native|stream-chat-react-native-core)"
    ]
`

**Comment by jaimebiernaski** [comment]
Hi @virdesai, I've tried but it didn't solve the issue.

Some days ago I've tried with this version of transformIgnorePatterns with `|stream-chat-expo|@stream-chat-expo/.|stream-chat-react-native-core|@stream-chat-react-native-core/.`

```
"transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.|react-navigation|@react-navigation/.| @unimodules/.|unimodules|sentry-expo|native-base|@sentry/.|stream-chat-expo|@stream-chat-expo/.|stream-chat-react-native-core|@stream-chat-react-native-core/.)"
    ]
```

But it gives the error

```
FAIL  ./App.test.js
  ● Test suite failed to run

    Cannot find module '../../../package.json' from 'Chat.js'

    Require stack:
      node_modules/stream-chat-react-native-core/lib/commonjs/components/Chat/Chat.js
      node_modules/stream-chat-react-native-core/lib/commonjs/components/index.js
      node_modules/stream-chat-react-native-core/lib/commonjs/index.js
      node_modules/stream-chat-expo/src/index.js
      App.js
      App.test.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:299:11)
```

It seems don't find the components. I guess this issue could be related to some `transform`, `moduleNameMapper`  or `preset` setup.

**Comment by virdesai** [comment]
@jaimebiernaski just want to test something before trying to make moves on our SDK side with our build process. can you try to go back to the point where the error was the package.json import. then go to `node_modules/stream-chat-react-native-core/lib` and creating a simple `package.json` like this and letting me know if that gets you past this error?
```
{
  "version": "2.2.0",
}
```
the directory structure of `lib` should then have 3 folders, `commonjs`, `module`, and `typescript`, and then the `package.json` you created

**Comment by jaimebiernaski** [comment]
Just a note: we are using the library  `"stream-chat-expo": "^2.0.0"`, provided by you and running the tests over the example available in the [stream website](https://getstream.io/chat/react-native-chat/tutorial/).  Is that relevant? Our project require using this libraries, once we are using expo in our apps...

**Comment by jaimebiernaski** [comment]
Hi @virdesai, I've tried the add the `package.json` an got different results :-)

```
➜  stream-chat-react-native-core git:(master) ✗ pwd
/.../stream-jest-error/node_modules/stream-chat-react-native-core
➜  stream-chat-react-native-core git:(master) ✗ ll                                           
total 168
-rw-r--r--   1 letz  staff    42K Jan 29 15:39 CHANGELOG.md
-rw-r--r--   1 letz  staff    14K Jan 29 15:39 LICENSE
-rw-r--r--   1 letz  staff    16K Jan 29 15:39 README.md
drwxr-xr-x   6 letz  staff   192B Feb  4 08:02 lib
drwxr-xr-x   9 letz  staff   288B Feb  2 11:59 node_modules
-rw-r--r--   1 letz  staff   6.3K Jan 29 15:39 package.json
drwxr-xr-x  15 letz  staff   480B Feb  2 11:54 src
```

The test passed, but it generate some errors related to the `Channel` and `Chat.tsx`

```
 PASS  ./App.test.js (13.702s)
  ✓ render (358ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        13.794s
Ran all test suites.

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at module.exports (node_modules/follow-redirects/debug.js:7:15)
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
  console.error
    Warning: An update to Channel inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
        in Channel
        in ThemeProvider (at ThemeContext.tsx:29)
        in ThemeProvider (at Chat.tsx:178)
        in TranslationProvider (at Chat.tsx:177)
        in ChatProvider (at Chat.tsx:176)
        in Chat
        in RCTSafeAreaView (created by RCTSafeAreaView)
        in RCTSafeAreaView (created by ForwardRef(SafeAreaView))
        in ForwardRef(SafeAreaView)
        in Unknown (created by App)
        in App

      at warningWithoutStack (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:131:32)

  console.error
    Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
        in Channel
        in ThemeProvider (at ThemeContext.tsx:29)
        in ThemeProvider (at Chat.tsx:178)
        in TranslationProvider (at Chat.tsx:177)
        in ChatProvider (at Chat.tsx:176)
        in Chat
        in RCTSafeAreaView (created by RCTSafeAreaView)
        in RCTSafeAreaView (created by ForwardRef(SafeAreaView))
        in ForwardRef(SafeAreaView)
        in Unknown (created by App)
        in App

      at warningWithoutStack (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:131:32)

```

Here is the Jest config

```
"jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|@sentry/.*|stream-chat-expo|@stream-chat-expo/.|stream-chat-react-native-core|@stream-chat-react-native-core/.)"
    ]
  },

```

**Comment by virdesai** [comment]
@jaimebiernaski does that fail your test or do your tests successfully pass? we have updates coming in general to a lot of components which may fix this but want to ensure we're getting your tests to pass at a base level first, isolated of warnings

**Comment by jaimebiernaski** [comment]
@virdesai, I still can not run tests without errors... Add package.json just solve part of it...  I'm still getting errors/warning related to the stream libs. Not sure if its a matter of setup, but this is occurring when stream components are used. Some setup needed besides that ones in my last comment in order to avoid this kind of issues?

```
 console.error
    Warning: An update to Channel inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
        in Channel
        in ThemeProvider (at ThemeContext.tsx:29)
        in ThemeProvider (at Chat.tsx:178)
        in TranslationProvider (at Chat.tsx:177)
        in ChatProvider (at Chat.tsx:176)
        in Chat
        in RCTSafeAreaView (created by RCTSafeAreaView)
        in RCTSafeAreaView (created by ForwardRef(SafeAreaView))
        in ForwardRef(SafeAreaView)
        in Unknown (created by App)
        in App
```

**Comment by klougod** [comment]
@virdesai Hi, after looking up, I realized that this issue may be resolved by shipping the library transpiled instead of leaving it to be built in the user side although it is possible to make jest compile libs using transform and adding presets, but its a complicated way and until now I could not make it work.

**Comment by virdesai** [comment]
@jaimebiernaski I'll try to look into this more at some point but I'm not sure if you're going to need to mock up a lot of stuff like we did within our tests for creating clients/channels with the API mocking too here https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/Channel/__tests__/Channel.test.js

**Comment by jaimebiernaski** [comment]
Ok @virdesai, it would be greate to have this working with no problems. This erros just occurs when components are imported from `stream-chat-expo` in the code 
```
import { Chat, Channel, MessageList, MessageInput } from 'stream-chat-expo';
``` 
I've mocked and tested the `stream-chat` with no problems.
```
import { StreamChat } from 'stream-chat';
```

**Comment by virdesai** [comment]
@jaimebiernaski the wrapping act warnings that are being thrown shouldn't be causing any actual issues. we see those in tests as just stuff piped out into the console but not stopping it from working

**Comment by jaimebiernaski** [comment]
@virdesai, so our best solution for making the 

**Stream & Expo + Jest + React Native Testing Library**  

work together is:

1. Use the `transformIgnorePatterns` proposed by  us in this [comment](https://github.com/GetStream/stream-chat-react-native/issues/508#issuecomment-773243858);
2. [Generate](https://github.com/GetStream/stream-chat-react-native/issues/508#issuecomment-772799433) a `package.json` inside of the folder `node_modules/stream-chat-react-native-core/lib` every time we exec `yarn install`;
3. Deal with a lot of `console.errors`& `warnings` of components imported from `stream-chat-expo`  in our tests.

I will not be able to add the step 2 manually inside the node_modules in our CI/CD that uses the `package.json` to install the `node_modules` and run all tests every time that occurs a repository merge. This will generate errors and block our pipeline. There is some planning of bug-fix addressing this issue in the lib `stream-chat-react-native-core` ?

**Comment by virdesai** [comment]
@jaimebiernaski yeah we'll definitely work on addressing the `package.json` issue in our build process

**Comment by jaimebiernaski** [comment]
Hi @virdesai , I found A work around but stills requires the manual `package.json` setup. I was working to fix that warnings problems, and looking in your repo, I've found the following [jest-setup.js](https://github.com/GetStream/stream-chat-react-native/blob/master/jest-setup.js)

```javascript
import { registerNativeHandlers } from './src/native';

// eslint-disable-next-line no-underscore-dangle
const _consoleE = console.error;
console.error = (e) => {
  // For some reason following error gets rased from waitFor function.
  // Source of the error is in react-test-renderer, although cause of the
  // issue is unknown. Until we figure out the proper way to fix this issue,
  // following hack should work. We just suppress this particular error.
  // It should be safe since the error is only raised in dev environment
  // https://github.com/facebook/react/blob/b683c07ccce340b9d687683d5dd7347a4c866787/packages/react-dom/src/test-utils/ReactTestUtilsAct.js#L121
  if (e.indexOf('You called act(async () => ...) without await') === -1) {
    _consoleE(e);
  }
};
console.warn = () => {};

registerNativeHandlers({
  NetInfo: {
    addEventListener: () => {},
    fetch: () =>
      new Promise((resolve) => {
        resolve();
      }),
  },
  pickDocument: () => null,
  pickImage: () => null,
});
```

I've create this file in my code, replacing the 

`import { registerNativeHandlers } from './src/native';` 
...
`e.indexOf('You called act(async () => ...) without await'`

with

`import { registerNativeHandlers } from 'stream-chat-react-native-core';`
...
` e.indexOf('An update to %s inside a test was not wrapped in act(...).')`

The final version of the jest setup in the `package.json`:

```
 "jest": {
    "preset": "jest-expo",
    "setupFiles": [
      "./jest-setup.js"
    ],
    "setupFilesAfterEnv": [
      "@testing-library/jest-native/extend-expect"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|@sentry/.*|stream-chat-expo|@stream-chat-expo/.*|stream-chat-react-native-core|@stream-chat-react-native-core/.*)"
    ]
  },
```

With it this was possible to run the test

My test file

```javascript
// App.test.js
import React from 'react';
import { render, waitFor } from '@testing-library/react-native';
import App from './App';

test('render', async () => {
  let wrapper;

  await waitFor(() => {
    wrapper = render(<App />);
  });

  expect(wrapper?.getByTestId('app')).toBeTruthy();
  jest.useFakeTimers();
});
```

My `jest.setup`

```
import 'react-native-gesture-handler/jestSetup';
import { registerNativeHandlers } from 'stream-chat-react-native-core';

jest.mock('react-native/Libraries/Animated/src/NativeAnimatedHelper');
jest.mock('react-native-reanimated', () => {
  const Reanimated = require('react-native-reanimated/mock');
  Reanimated.default.call = () => {};
  return Reanimated;
});

const _consoleE = console.error;
console.error = (e) => {
  // For some reason following error gets rased from waitFor function.
  // Source of the error is in react-test-renderer, although cause of the
  // issue is unknown. Until we figure out the proper way to fix this issue,
  // following hack should work. We just suppress this particular error.
  // It should be safe since the error is only raised in dev environment
  // https://github.com/facebook/react/blob/b683c07ccce340b9d687683d5dd7347a4c866787/packages/react-dom/src/test-utils/ReactTestUtilsAct.js#L121
  if (
    e.indexOf('An update to %s inside a test was not wrapped in act(...).') ===
    -1
  ) {
    _consoleE(e);
  }
};
console.warn = () => {};

registerNativeHandlers({
  NetInfo: {
    addEventListener: () => {},
    fetch: () =>
      new Promise((resolve) => {
        resolve();
      }),
  },
  pickDocument: () => null,
  pickImage: () => null,
});

```

The test result
```
➜  stream-jest-error git:(master) ✗ yarn jest --detectOpenHandles 
yarn run v1.22.4
$ /.../stream-jest-error/node_modules/.bin/jest --detectOpenHandles
 PASS  ./App.test.js
  ✓ render (217ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        4.551s
Ran all test suites.
```

Please, keep this issue open until we have the fix for the `node_modules/stream-chat-react-native-core/lib/package.json`

**Comment by virdesai** [comment]
@jaimebiernaski merged in a fix for the versioning issue https://github.com/GetStream/stream-chat-react-native/pull/553
should be out with a new release that we plan on pushing soon

**Comment by jaimebiernaski** [comment]
Thanks!


Jaime Biernaski

Keep your dreams alive!

**Comment by vishalnarkhede** [comment]
@jaimebiernaski we have published `v3.1.0`, where this issue should be fixed. Could you please confirm?

**Comment by jaimebiernaski** [comment]
Hi,

We are working on a critical rollout process. When possible I'll check
this. Thanks!


*Jaime Biernaski*
***@***.*** ***@***.***>*
*Skype: jaime.biernaski*


*Keep your dreams alive!*

**Comment by ste7en** [comment]
Still having this issue, despite any of the above mentioned solutions. 

My jest.config.js:
```module.exports = {
  preset: 'react-native',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  moduleNameMapper: {
    '\\.(jpg|ico|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      'identity-obj-proxy',
    '@/(.*)': '<rootDir>/src/$1',
    '\\.svg': '<rootDir>/__mocks__/svgMock.js'
  },
  testEnvironment: 'jsdom',
  setupFiles: ['./config/jest.setup.js', './node_modules/react-native-gesture-handler/jestSetup.js'],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.test.{ts,tsx}',
    '!src/**/*.stories.{ts,tsx}',
    '!src/App.tsx',
    '!src/store.ts',
    '!src/models/**',
    '!**/node_modules/**'
  ],
  transformIgnorePatterns: [
    'node_modules/(?!(@react-native|react-native|react-native-(.+))/)'
  ]
}
```

jest.setup.js : 
```import mockAsyncStorage from '@react-native-async-storage/async-storage/jest/async-storage-mock'
import 'react-native-gesture-handler/jestSetup'

jest.mock('@react-native-async-storage/async-storage', () => mockAsyncStorage)
jest.mock('react-native/Libraries/Animated/NativeAnimatedHelper')
```

and finally the error from Jest: 
```    Details:

    /Users/omitted/Developer/VPC/node_modules/stream-chat-react-native/src/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import React from 'react';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

       6 | import {SafeAreaView} from 'react-native-safe-area-context'
       7 | import {Channel} from 'stream-chat'
    >  8 | import {ChannelList} from 'stream-chat-react-native'
         | ^
       9 |
      10 | import Button from '@/Components/Button/Button'
      11 | import ChannelPreview from '@/Components/Chat/ChannelPreview/ChannelPreview'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/Containers/MessagesScreen/MessagesScreen.tsx:8:1)
```

Any guide on how to setup Jest correctly?

**Comment by finalight** [comment]
still encountering this issue, any solutions?

**Comment by PhilVargas** [comment]
Seeing this issue on v5.14.1. 

```
SyntaxError: Cannot use import statement outside a module
```

Is there any documentation on testing an application with jest using the getstream sdk?
